services:
  ros-dev:
    container_name: ros-noetic-dev
    build:
      context: . 
      dockerfile: Dockerfile
      args:
        USERNAME: matt
        USER_UID: 1000
    image: matt/ros-noetic:latest
    command: sleep infinity
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - QT_AUTO_SCREEN_SCALE_FACTOR=1
    volumes:
      # Mount BT_projects to /workspaces/BT_projects
      - /home/matt/BT_projects:/workspaces/BT_projects:cached
      
      # Mount tagslam_ros2_root to /workspaces/tagslam_ros2_root
      - /home/matt/tagslam_ros2_root:/workspaces/tagslam_ros2_root:cached

      # Mount getting-started-threejs to /workspaces/getting-started-threejs
      - /home/matt/getting-started-threejs:/workspaces/getting-started-threejs:cached
      

      #- ..:/workspaces:cached
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    devices:
      - /dev/dri:/dev/dri
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
